apps/loginRegistration_app/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
    url(r'^logout$', views.logout, name='logout'),
    # url(r'^dashboard$', views.index, name='index'),
    # url(r'^user/(?P<id>\d+)$', views.show_user, name='show_user'),
    # url(r'^recipe/(?P<recipe_id>\d+)$', views.show_recipe, name='show_recipe'),
    # url(r'^add_recipe$', views.add_recipe, name='add_recipe'),
    # url(r'^delete_recipe/(?P<recipe_id>\d+)$', views.delete_recipe, name='delete_recipe'),
    # url(r'^edit_recipe/(?P<recipe_id>\d+)$', views.edit_recipe, name='edit_recipe'),
    # url(r'^add_step$', views.add_step, name='add_step'),
    # url(r'^add_rating(?P<recipe_id>\d+)$', views.add_rating, name='add_rating'),
    # url(r'^save_recipe(?P<recipe_id>\d+)$', views.save_recipe, name='save_recipe'),
    # url(r'^update_step/(?P<step_id>\d+)$', views.update_step, name='update_step'),
    # url(r'^delete_step/(?P<step_id>\d+)$', views.delete_step, name='delete_step'),
    # url(r'^search$', views.search, name='search'),
]

potLuck/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('apps.loginRegistration_app.urls', namespace='loginReg')),
    url(r'^', include('apps.cooking_app.urls', namespace='main'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.STATIC_ROOT}),
    ]

apps/loginRegistration_app/models.py
from __future__ import unicode_literals

from django.db import models
import re  #regex
import bcrypt  #encryption
# from django.contrib import messages #to display errors
# from datetime import datetime
# from django.core.exceptions import ValidationError

# Create your models here.
class UserManager(models.Manager):
	def RegisterValidation(self, form_info):
		if 'password' in form_info:
			return False

		errors = []
		EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
		first_name = form_info['first_name']
		last_name = form_info['last_name']
		email = form_info['email']
		password1 = form_info['password1']
		password2 = form_info['password2']
		if  len(User.objects.all()) < 1:
			user_level = 9
		else:
			user_level = 1

		if len(email)<1:
			errors.append('No email entered.')
		elif not EMAIL_REGEX.match(email):
			errors.append('Not a valid email.')
		elif User.objects.filter(email=email):
			errors.append('Email already in use.')

		if len(first_name) < 2 or len(first_name) < 2:
			errors.append('First and last name must be longer than 2 characters.')

		if password1 != password2:
			errors.append('Passwords do not match.')
		elif len(password1)<8:
			errors.append('Password must be at least 8 characters.')

		if len(errors) > 0:
			return (errors)
		else:
			password = str(password1)
			hashed = bcrypt.hashpw(password, bcrypt.gensalt())
			User.objects.create(first_name=first_name, last_name=last_name,email=email, password=hashed, user_level=user_level, description=None)
			user = User.objects.get(email=email)
			# request.session['id'] = user.id
			# request.session['user_level'] = user.user_level
			return (errors, user.id, user.user_level)

	def LoginValidation(self, form_info):
		errors = []
		email = form_info['email']
		password = form_info['password']
		if len(User.objects.filter(email=email))<1:
			errors.append('Invalid login information.')
			return (errors)
		user = User.objects.get(email=email)
		password_entered = password.encode()
		hashed_entered = bcrypt.hashpw(password_entered, bcrypt.gensalt())
		if email == user.email and bcrypt.hashpw(password_entered, user.password.encode()) == user.password:
			# request.session['id'] = user.id
			# request.session['user_level'] = user.user_level
			return (errors, user.id, user.user_level)
		else:
			errors.append('Password incorrect.')
			return (errors)

class UserPicManager(models.Manager):
	def pic(self, post, files, user_id):
		if len(UserPic.objects.filter(user=User.objects.get(id=user_id))) > 0:
			pic = UserPic.objects.get(user=User.objects.get(id=user_id))
			pic.image = files['image']
			pic.save()
			return pic
		else:
			return UserPic.objects.create(user=User.objects.get(id=user_id), image=files['image'])

class User(models.Model):
	first_name = models.CharField(max_length=255)
	last_name = models.CharField(max_length=255)
	email = models.CharField(max_length=255)
	password = models.CharField(max_length=255)
	user_level = models.IntegerField()
	description = models.CharField(max_length=255, null=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	objects = UserManager()

class UserPic(models.Model):
	image = models.ImageField(upload_to='UserPics')
	user = models.OneToOneField('User', on_delete=models.CASCADE, related_name='pic')
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	objects = UserPicManager()

apps/loginRegistration_app/views.py
from django.shortcuts import render, redirect
from .models import User, UserPic
from django.contrib import messages
# import datetime
# from django.http import JsonResponse
# from .forms import PicsForm
# from django.db.models import Q




def login(request):
	if request.method == "POST":
		results = User.objects.LoginValidation(request.POST)
		if len(results[0])<1:
			request.session['id'] = results[1]
			request.session['user_level'] = results[2]
			return redirect('main:index')
		else:
			for error in results:
				messages.error(request, error)
	return render(request, 'loginRegistration/login.html')


def register(request):
	if request.method == "POST":
		results = User.objects.RegisterValidation(request.POST)
		if len(results[0])<1:
			request.session['id'] = results[1]
			request.session['user_level'] = results[2]
			return redirect('main:index')
		else:
			for error in results:
				messages.error(request, error)
	return render(request, 'loginRegistration/register.html')


def logout(request):
	for key in request.session.keys():
		del request.session[key]
	return redirect('main:welcome')

apps/loginRegistration_app/templates/loginRegistration/login.html
<!DOCTYPE html>
<html>
<head>
	<title>potluck/login</title>
	<!-- Latest compiled and minified CSS -->
	<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->

	<!-- Optional theme -->
	<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

	<!-- Latest compiled and minified JavaScript -->
	<!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> -->
	<link rel="stylesheet" href="../../static/cooking_app/css/bootstrap.min.css">
	<link rel="stylesheet" href="../../static/cooking_app/css/logreg.css">
	<script src="../../static/cooking_app/js/jquery-3.1.1.min.js" charset="utf-8"></script>
	<script src="../../static/cooking_app/js/bootstrap.min.js" charset="utf-8"></script>
	<style>
		a:link{
			color: black;
		}
	</style>
</head>
<body>

	<div class='container'>
		<div id="header">
			<h1><img src="../../static/cooking_app/images/gold1.png" alt=""><span id="title">potLuck</span></h1>
			<p>Because shared food is best food</p>
		</div>
		<div id="form">
			<h3>Login</h3>
			<form action="{% url 'loginReg:login' %}" method="post" class='form-horizontal'>
				{% csrf_token %}
				<div class="form-group">
					<div class="col-sm-12 col-md-12 col-lg-12">
						<p>Email:	<input type="text" name="email" class='form-control'></p>
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-12 col-md-12 col-lg-12">
						<p>Password:<input type="password" name="password" class='form-control'></p>
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-10">
						<input type="submit" value="Login" class='btn btn-danger'>
					</div>
				</div>
			</form>
		<!-- </div> -->

			{% if messages %}
			<ul class="messages">
			    {% for message in messages %}
			    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			    {% endfor %}
			</ul>
			{% endif %}

			<br>
			<a href="{% url 'loginReg:register' %}">Not a member? Register here for free!</a>
		</div>
	</div>
</body>
</html>

apps/loginRegistration_app/templates/loginRegistration/register.html
<!DOCTYPE html>
<html>
<head>
	<title>potluck | register</title>
	<link rel="stylesheet" href="../../static/cooking_app/css/bootstrap.min.css">
	<link rel="stylesheet" href="../../static/cooking_app/css/logreg.css">
	<script src="../../static/cooking_app/js/jquery-3.1.1.min.js" charset="utf-8"></script>
	<script src="../../static/cooking_app/js/bootstrap.min.js" charset="utf-8"></script>
</head>
<body>

	<div id="container">
		<div id="header">
			<h1><img src="../../static/cooking_app/images/gold1.png" alt=""><span id="title">potLuck</span></h1>
			<p>Because shared food is best food</p>
		</div>
		<div id="form">
			<h3>Register</h3>
			<form action="{% url 'loginReg:register' %}" method="post" class='form-horizontal'>
				{% csrf_token %}
				<div class="form-group">
					<div class="col-sm-12 col-md-12 col-lg-12">
						<p>First Name: <input type="text" name="first_name" class='form-control'></p>
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-12 col-md-12 col-lg-12">
						<p>Last Name: <input type="text" name="last_name" class='form-control'></p>
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-12 col-md-12 col-lg-12">
						<p>Email:	<input type="text" name="email" class='form-control'></p>
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-12 col-md-12 col-lg-12">
						<p>Password:<input type="password" name="password1" class='form-control'></p>
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-12 col-md-12 col-lg-12">
						<p>Confirm Password:<input type="password" name="password2" class='form-control'></p>
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-10">
						<input type="submit" class='btn btn-danger' value="Register">
					</div>
				</div>
			</form>

			{% if messages %}
			<ul class="messages">
				{% for message in messages %}
				<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
				{% endfor %}
			</ul>
			{% endif %}

			<br>
			<a href="{% url 'loginReg:login' %}">Already have an account? Login here!</a>
		</div>
	</div>
</body>
</html>