apps/cooking_app/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^$', views.welcome, name='welcome'),
    url(r'^dashboard$', views.index, name='index'),
    url(r'^user/(?P<id>\d+)$', views.show_user, name='show_user'),
    url(r'^recipe/(?P<recipe_id>\d+)$', views.show_recipe, name='show_recipe'),
    url(r'^add_recipe$', views.add_recipe, name='add_recipe'),
    url(r'^delete_recipe/(?P<recipe_id>\d+)$', views.delete_recipe, name='delete_recipe'),
    url(r'^edit_recipe/(?P<recipe_id>\d+)$', views.edit_recipe, name='edit_recipe'),
    url(r'^add_step$', views.add_step, name='add_step'),
    url(r'^add_rating(?P<recipe_id>\d+)$', views.add_rating, name='add_rating'),
    url(r'^save_recipe(?P<recipe_id>\d+)$', views.save_recipe, name='save_recipe'),
    url(r'^update_step/(?P<step_id>\d+)$', views.update_step, name='update_step'),
    url(r'^delete_step/(?P<step_id>\d+)$', views.delete_step, name='delete_step'),
    url(r'^search$', views.search, name='search'),
]

apps/loginRegistration_app/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
    url(r'^logout$', views.logout, name='logout'),
    # url(r'^dashboard$', views.index, name='index'),
    # url(r'^user/(?P<id>\d+)$', views.show_user, name='show_user'),
    # url(r'^recipe/(?P<recipe_id>\d+)$', views.show_recipe, name='show_recipe'),
    # url(r'^add_recipe$', views.add_recipe, name='add_recipe'),
    # url(r'^delete_recipe/(?P<recipe_id>\d+)$', views.delete_recipe, name='delete_recipe'),
    # url(r'^edit_recipe/(?P<recipe_id>\d+)$', views.edit_recipe, name='edit_recipe'),
    # url(r'^add_step$', views.add_step, name='add_step'),
    # url(r'^add_rating(?P<recipe_id>\d+)$', views.add_rating, name='add_rating'),
    # url(r'^save_recipe(?P<recipe_id>\d+)$', views.save_recipe, name='save_recipe'),
    # url(r'^update_step/(?P<step_id>\d+)$', views.update_step, name='update_step'),
    # url(r'^delete_step/(?P<step_id>\d+)$', views.delete_step, name='delete_step'),
    # url(r'^search$', views.search, name='search'),
]

potLuck/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('apps.loginRegistration_app.urls', namespace='loginReg')),
    url(r'^', include('apps.cooking_app.urls', namespace='main'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.STATIC_ROOT}),
    ]

apps/cooking_app/forms.py
from django import forms

class PicsForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

apps/cooking_app/views.py
from django.shortcuts import render, redirect, reverse
from .models import Comment, Recipe, Ingredient, Measurement, Step, RecipePic, Rating, Category
from ..loginRegistration_app.models import User, UserPic
from django.contrib import messages
import datetime
from django.http import JsonResponse
from .forms import PicsForm
from django.db.models import Q


# Create your views here.
def welcome(request):
	return redirect("loginReg:login")


def index(request):
	if 'id' not in request.session:
		return redirect('loginReg:login')
	context ={
		'user_name': User.objects.get(id=request.session['id']).first_name,
		'recipes': Recipe.objects.all().order_by('-updated_at'),
	}
	return render(request, 'cooking_app/index.html', context)


def show_recipe(request, recipe_id):
	if 'id' not in request.session:
		return redirect('loginReg:login')

	if request.method == 'POST':
		post = Comment.objects.create(comment=request.POST['comment'], user=User.objects.get(id=request.session['id']), recipe=Recipe.objects.get(id=recipe_id))
		return redirect(reverse('main:show_recipe', kwargs={'recipe_id': recipe_id}))

	recipe = Recipe.objects.get(id=recipe_id)
	ratings = recipe.ratings.all()
	sum_rating = 0.
	if len(ratings)>0:
		for rating in ratings:
			sum_rating += rating.rating
		avg_rating = sum_rating / len(ratings)
	else:
		avg_rating = 'No ratings yet.'

	total_time_hour = recipe.prep_time_hour + recipe.cook_time_hour
	total_time_minute = recipe.prep_time_minute + recipe.cook_time_minute

	if len(Rating.objects.filter(user=request.session['id'], recipe=recipe_id))>0:
		rating = False
	else:
		rating = True

	context = {
		'user': User.objects.get(id=request.session['id']),
		'recipe': recipe,
		'avg_rating': avg_rating,
		'total_time_hour': total_time_hour,
		'total_time_minute': total_time_minute,
		'rating': rating,
	}
	return render(request, 'cooking_app/show_recipe.html', context)


def add_recipe(request):
	if 'id' not in request.session:
		return redirect('loginReg:login')

	if request.method == 'POST': # if 'POST' we are trying to add something, else trying to display form to add
		errors = Recipe.objects.validateRecipe(request.POST) #run validations. returns errors if failed
		if len(errors) > 0:
			for error in errors:
				messages.error(request, error)
			return redirect('main:add_recipe')

		#create the recipe if validations passed
		recipe = Recipe.objects.create(title=request.POST['title'], creator=User.objects.get(id=request.session['id']), description=request.POST['description'], prep_time_hour=request.POST['prep_time_hour'], prep_time_minute=request.POST['prep_time_minute'], cook_time_hour=request.POST['cook_time_hour'], cook_time_minute=request.POST['cook_time_minute'])
		#Add Categories
		Category.objects.addCategory(request.POST, recipe)

		#add image
		if 'image' in request.FILES:
			RecipePic.objects.create(title=request.POST['title'], image=request.FILES['image'], recipe=recipe)

		#redirect to edit page so user can add steps to recipe
		return redirect(reverse('main:edit_recipe', kwargs={'recipe_id': recipe.id}))

	return render(request, 'cooking_app/add_recipe.html', {'user': User.objects.get(id=request.session['id']), 'categories': Category.objects.create_categories()})


def edit_recipe(request, recipe_id):
	if 'id' not in request.session:
		return redirect('loginReg:login')

	if request.method == 'POST': # if 'POST' we are trying to update recipe, else trying to display edit page
		#TODO: Implement updating of photo
		# if 'image' in request.FILES:
		# 	RecipePic.objects.update(recipe_id, request.Files)
		if 'title' in request.POST:
			errors = Recipe.objects.validateRecipe(request.POST)
			if len(errors) > 0: # run validations. returns errors if failed
				for error in errors:
					messages.error(request, error)
				return redirect('main:edit_recipe')
			else:
				Recipe.objects.update(request.POST, recipe_id) # passed validation, not update

	context = {
		'user': User.objects.get(id=request.session['id']),
		'recipe': Recipe.objects.get(id=recipe_id),
		'ingredients': Ingredient.objects.all().order_by('ingredient'),
		'measurements': Measurement.objects.all().order_by('measurement'),
		'categories': Category.objects.all(),
	}
	return render(request, 'cooking_app/edit_recipe.html', context)


def delete_recipe(request, recipe_id):
	if 'id' not in request.session:
		return redirect('loginReg:login')

	Recipe.objects.get(id=recipe_id).delete()
	return redirect('main:index')


def add_step(request):
	if 'id' not in request.session:
		return redirect('loginReg:login')

	step = Step.objects.add_step(request.POST) # runs code to validate step and return step after creation
	return redirect(reverse('main:edit_recipe', kwargs={'recipe_id': step.recipe.id}))


def update_step(request, step_id):
	if 'id' not in request.session:
		return redirect('loginReg:login')

	step = Step.objects.update_step(request.POST, step_id) # runs code to validate step and return step after update
	return redirect(reverse('main:edit_recipe', kwargs={'recipe_id': step.recipe.id}))


def delete_step(request, step_id):
	if 'id' not in request.session:
		return redirect('loginReg:login')

	Step.objects.get(id=step_id).delete()
	return JsonResponse({'to_delete': step_id})


def show_user(request, id):
	if 'id' not in request.session:
		return redirect('loginReg:login')

	if request.method == 'POST':
		if 'image' in request.FILES:
			user_pic = UserPic.objects.pic(request.POST, request.FILES, id)
	else:
		if len(UserPic.objects.filter(user=User.objects.get(id=id))) > 0:
			user_pic = UserPic.objects.get(user=User.objects.get(id=id))
		else:
			user_pic = ''

	context = {
		'self': User.objects.get(id=request.session['id']),
		'user': User.objects.get(id=id),
	}
	return render(request, 'cooking_app/show_user.html', context)


def add_rating(request, recipe_id):
	if 'id' not in request.session:
		return redirect('loginReg:login')

	Rating.objects.add_rating(recipe_id, request.session['id'], request.POST)
	return redirect(reverse('main:show_recipe', kwargs={'recipe_id':recipe_id}))


def save_recipe(request, recipe_id):
	if 'id' not in request.session:
		return redirect('loginReg:login')

	user = User.objects.get(id=request.session['id'])
	recipe = Recipe.objects.get(id=recipe_id)
	if user in recipe.user.all():
		recipe.user.remove(user)
	else:
		recipe.user.add(user)
	recipe.save()
	return redirect(reverse('main:show_recipe', kwargs={'recipe_id':recipe_id}))


def search(request):
	if 'id' not in request.session:
		return redirect('loginReg:login')

	results = []
	if request.method == 'POST':
		results = Recipe.objects.filter(Q(title__icontains=request.POST['search']) | Q(description__icontains=request.POST['search']))
		if request.POST['category'] != 'noCategory':
			category = Category.objects.get(id=request.POST['category'])
			results = results.filter(categories=category)

	context = {
		'results': results,
		'user': User.objects.get(id=request.session['id']),
		'categories': Category.objects.all(),
	}
	return render(request, 'cooking_app/search.html', context)










#

apps/cooking_app/templates/cooking_app/edit_recipe.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Add Your recipe!</title>
        <link rel="stylesheet" href="../../static/cooking_app/css/bootstrap.min.css">
        <script src="../../static/cooking_app/js/jquery-3.1.1.min.js" charset="utf-8"></script>
        <script src="../../static/cooking_app/js/bootstrap.min.js" charset="utf-8"></script>
        {% load staticfiles %}
        <script src="{% static 'cooking_app/js/js.cookie.js' %}"></script>
        <link rel="stylesheet" href="../../static/cooking_app/css/add.css">
        <script>
            $(document).ready(function(){
                $('#steps').on('submit', '#new_step_form', function(e){
                    e.preventDefault();
                    $.post(this.action, $(this).serialize(), function(serverResponse){
                        $('#steps').html($(serverResponse).find('#steps').html())
                    });
                });
                $('#form').on('focusout', '#update_recipe_form', function(){
                    $.post(this.action, $(this).serialize(), function(serverResponse){
                        // TODO: Show any errors
                    });
                });
                $('#steps').on('focusout', '.update_step', function(){
                    $.post(this.action, $(this).serialize(), function(serverResponse){
                        // TODO: if new measurement/ingredient was added update that
                    });
                });

                //TODO: FIX DELETE
                $('#steps').on('click', '.link', function(e){
                    e.preventDefault();
                    $.get($(this).attr('href'), function(serverResponse){
                        // $('#div_'+serverResponse.to_delete).siblings().find('.divider').prevObject[2].remove();
                        $('#div_'+serverResponse.to_delete).remove();
                    });
                });
            });
        </script>
    </head>
    <body>
        <div class="container">
            <div class="container-fluid">
                <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                            </button>
                            <a class="navbar-brand" href="{% url 'main:index' %}"><img src="../../static/cooking_app/images/gold1.png" alt=""></a>
            				<p class='navbar-text navbar-left'>Hello, {{user.first_name}}!</p>
                        </div>
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav navbar-right">
                                <li><a href="{% url 'main:index' %}">Home</a></li>
                                <li><a href="{% url 'main:show_user' id=request.session.id %}">Profile</a></li>
                                <li><a href="{% url 'main:add_recipe' %}">Add a Recipe</a></li>
                                <li><a href="{% url 'main:search' %}">Search</a></li>
                                <li><a href="{% url 'loginReg:logout' %}">Logout</a></li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <div class="main">
                    <div id="header">
                        <h1>Edit your Recipe!</h1>
                        <p class='para'>Here you are able to edit your own recipe and add anything that you may have missed!</p>
                    </div>

                    {% if messages %}
                        {% for message in messages %}
                            <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                        {% endfor %}
                    {% endif %}

                    <div>
                        <div id="form">
                            <form id="update_recipe_form" action="{% url 'main:edit_recipe' recipe_id=recipe.id%}" method="post" class='form-horizontal edit'>
                                {% csrf_token %}
                                <div class="form-group">
                                    <label>Recipe Title: <input type="text" name="title" value="{{recipe.title}}" class='form-control'></label>
                                </div>
                                <div class="form-group">
                                    <label>Prep Time: <input type="number" name="prep_time_hour" value="{{recipe.prep_time_hour}}" min="0" class='form-control inline time'> hrs </label>
                                    <label><input type="number" name="prep_time_minute" value="{{recipe.prep_time_minute}}" min="0" class='form-control inline time'> min</label><br>
                                </div>
                                <div class="form-group">
                                    <label>Cook Time: <input type="number" name="cook_time_hour" value="{{recipe.cook_time_hour}}" min="0" class='form-control inline time'> hrs</label>
                                    <label><input type="number" name="cook_time_minute" value="{{recipe.cook_time_minute}}" min="0" class='form-control inline time'> min</label><br>
                                </div>
                                <div class="form-group">
                                    <label><span class="vert_align">Description:</span> <textarea name="description" rows="3" cols="25" class='form-control'>{{recipe.description}}</textarea></label><br>
                                </div>
                                <div class="form-group">
                                    <p><label>Categories:</label></p>
                                    {% for category in categories %}
                                        {% if category in recipe.categories.all %}
                                            <input class='checkbox inline' type="checkbox" name="{{category.category}}" value="{{category.id}}" checked> {{category.category}}
                                        {% else %}
                                            <input class='checkbox inline' type="checkbox" name="{{category.category}}" value="{{category.id}}"> {{category.category}}
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            </form>
                            <a href="{% url 'main:delete_recipe' recipe_id=recipe.id %}"><button class='btn btn-danger'>Delete Recipe</button></a> <a href="{% url 'main:show_recipe' recipe_id=recipe.id %}"><button class='btn btn-success'>View Recipe</button></a>
                            <div class="foodpic">
                                {% if recipe.recipe_image %}
                                    <img id="recipe_img" class='img-responsive' src="{{recipe.recipe_image.image.url}}">

                                {% endif %}
                            </div>
                        </div>
                        <!-- add form to update food pic -->
                        <!--         <form enctype="multipart/form-data" action="{% url 'main:edit_recipe' recipe_id=recipe.id %}" method="post">
                        {% csrf_token %}
                        <label>Change Image: <input type="file" name="image"></label><br>
                        <input type="submit" value="Update Image">
                        </form> -->
                    </div>
                    <hr>
                    <div id="steps">
                        <h3>Update your steps</h3>
                        <div class="row">
                            <p class="col-sm-1 bold">Step #</p>
                            <p class="col-sm-3 bold">Measurement</p>
                            <p class="col-sm-3 bold">Ingredient</p>
                            <p class="col-sm-3 bold">Description</p>
                            <p class="col-sm-2 bold">Actions</p>
                        </div>
                        {% for step in recipe.steps.all %}
                            <div id='div_{{step.id}}' class='row'>
                                <form id='{{step.id}}' class='update_step' action="{% url 'main:update_step' step_id=step.id%}" method="post">
                                    {% csrf_token %}
                                    <p class="col-sm-1">{{ forloop.counter }}</p>
                                    <div class="col-sm-3">
                                        <select name='measurement'>
                                            {% for measurement in measurements %}
                                                {% if measurement ==  step.measurement %}
                                                    <option selected="selected" value="{{measurement.id}}">{{measurement.measurement}}</option>
                                                {% else %}
                                                    <option value="{{measurement.id}}">{{measurement.measurement}}</option>
                                                {% endif %}
                                            {% endfor %}
                                        </select>
                                        <input type="text" name="new_measurement" placeholder="Add new measurement" class='form-control'>
                                    </div>
                                    <div class="col-sm-3">
                                        <select name='ingredient'>
                                            {% for ingredient in ingredients %}
                                                {% if ingredient == step.ingredient %}
                                                    <option selected="selected" value="{{ingredient.id}}">{{ingredient.ingredient}}</option>
                                                {% else %}
                                                    <option value="{{ingredient.id}}">{{ingredient.ingredient}}</option>
                                                {% endif %}
                                            {% endfor %}
                                        </select>
                                        <input type="text" name="new_ingredient" placeholder="Add new ingredient" class='form-control'>
                                    </div>
                                    <div class="col-sm-3">
                                        <textarea name="description" rows="2" cols="25" class='form-control'>{{step.description}}</textarea></label>
                                        <input type="hidden" name="step_id" value="{{step.id}}">
                                    </div>
                                </form>
                                <div class="col-sm-2">
                                    <a class='link' href="{% url 'main:delete_step' step_id=step.id %}"><button class='btn btn-danger'>Delete Step</button></a>
                                </div>
                                <hr>
                            </div>
                            <!-- <div class="divider"> -->
                                <!-- <div class="spacing"></div> -->
                                <!-- <hr> -->
                                <!-- <div class="spacing"></div> -->
                            <!-- </div> -->
                        {% endfor %}
                        <div class="row">
                            <form id='new_step_form' class='new_step form-horizontal' action="{% url 'main:add_step' %}" method="post">
                                {% csrf_token %}
                                <p class="col-sm-1">Add New</p>
                                <div class="col-sm-3">
                                    <select name='measurement'>
                                        {% for measurement in measurements %}
                                        <option value="{{measurement.id}}">{{measurement.measurement}}</option>
                                        {% endfor %}
                                    </select>
                                    <input type="text" name="new_measurement" placeholder="Add new measurement" class='form-control'>
                                </div>
                                <div class="col-sm-3">
                                    <select name='ingredient'>
                                        {% for ingredient in ingredients %}
                                        <option value="{{ingredient.id}}">{{ingredient.ingredient}}</option>
                                        {% endfor %}
                                    </select>
                                    <input type="text" name="new_ingredient" placeholder="Add new ingredient" class='form-control'>
                                </div>
                                <div class="col-sm-3">
                                    <textarea name="description" rows="2" cols="25" class='form-control'></textarea>
                                    <input type="hidden" name="recipe_id" value="{{recipe.id}}">
                                </div>
                                <div class="col-sm-2">
                                    <input type="submit" value="Add Step" class='btn btn-success'>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>










<!--  -->

apps/cooking_app/templates/cooking_app/index.html
<!DOCTYPE html>
<html>
<head>
	<title>potLuck</title>
	<link rel="stylesheet" href="../../static/cooking_app/css/bootstrap.min.css">
	<link rel="stylesheet" href="../../static/cooking_app/css/dash.css">
	<script src="../../static/cooking_app/js/jquery-3.1.1.min.js" charset="utf-8"></script>
	<script src="../../static/cooking_app/js/bootstrap.min.js" charset="utf-8"></script>
</head>
<body id='page-top'>
	<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{% url 'main:index' %}"><img src="../../static/cooking_app/images/gold1.png" alt=""></a>
								<p class='navbar-text navbar-left'>Hello, {{user_name}}!</p>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
					<li><a href="{% url 'main:index' %}">Home</a></li>
                    <li><a href="{% url 'main:show_user' id=request.session.id %}">Profile</a></li>
                    <li><a href="{% url 'main:add_recipe' %}">Add a Recipe</a></li>
                    <li><a href="{% url 'main:search' %}">Search</a></li>
                    <li><a href="{% url 'loginReg:logout' %}">Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>

	<div class="container main">
		<h1><span>Welcome to </span><br><img class='logo' src="../../static/cooking_app/images/gold1.png" alt=""> potLuck!</h1>
		<hr>
		<h2>What's on today's menu?</h2>
		<div id="recipes">
			{% for recipe in recipes %}
				<div class="recipe col-xs-6">
					<h3>{{recipe.title}}</h3>
					{% if recipe.recipe_image %}
						<div class="bg">
							<img class='recipe_img' src="{{recipe.recipe_image.image.url}}">
						</div>
					{% endif %}
					<div class='recipe_info'>
						<p><b>Prep Time:</b> {{recipe.prep_time_hour}} hour(s), {{recipe.prep_time_minute}} minutes.</p>
						<p><b>Cook Time:</b> {{recipe.cook_time_hour}} hour(s), {{recipe.cook_time_minute}} minutes.</p>
						<p><b>Created by: </b><a href="{% url 'main:show_user' id=recipe.creator.id %}">{{recipe.creator.first_name}} {{recipe.creator.last_name}}</a></p>
						<a class='ingredient' href="{% url 'main:show_recipe' recipe_id=recipe.id %}">Ingredient List</a>
					</div>
				</div>
			{% endfor %}
		</div>
		<!-- <div id="sidebar">
			<h3>Random Recipes</h3>
		</div> -->
	</div>
</body>
</html>

apps/cooking_app/templates/cooking_app/show_recipe.html
<!DOCTYPE html>
<html>
<head>
	<title>Recipe</title>
	<link rel="stylesheet" href="../../static/cooking_app/css/bootstrap.min.css">
	<link rel="stylesheet" href="../../static/cooking_app/css/add.css">
	<script src="../../static/cooking_app/js/jquery-3.1.1.min.js" charset="utf-8"></script>
	<script src="../../static/cooking_app/js/bootstrap.min.js" charset="utf-8"></script>
</head>
<body>
	<div class="container">
		<div class="container-fluid">
			<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							<span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
						</button>
						<a class="navbar-brand" href="{% url 'main:index' %}"><img src="../../static/cooking_app/images/gold1.png" alt=""></a>
						<p class='navbar-text navbar-left'>Hello, {{user.first_name}}!</p>
					</div>
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<ul class="nav navbar-nav navbar-right">
							<li><a href="{% url 'main:index' %}">Home</a></li>
							<li><a href="{% url 'main:show_user' id=request.session.id %}">Profile</a></li>
							<li><a href="{% url 'main:add_recipe' %}">Add a Recipe</a></li>
							<li><a href="{% url 'main:search' %}">Search</a></li>
							<li><a href="{% url 'loginReg:logout' %}">Logout</a></li>
						</ul>
					</div>
				</div>
			</nav>
			<div class="main">
				<h1>{{recipe.title}}</h1>
			<div id="info">
				{% if recipe.recipe_image %}
					<div class="bg">
						<img id="recipe_img" style="width: auto; height: 150px;" src="{{recipe.recipe_image.image.url}}">
					</div>
				{% endif %}
				<div class="info">
					{% if avg_rating == 'No ratings yet.' %}
						<p><b>{{avg_rating}}</b></p>
					{% else %}
						<p><b>Rating: {{avg_rating|floatformat}} / 5</b></p>
					{% endif %}
					{% if request.session.id != recipe.creator.id and rating %}
						<form action="{% url 'main:add_rating' recipe_id=recipe.id%}" method="post" class='form-inline'>
							{% csrf_token %}
							<div class="form-group">
								<select name="rating" class='form-control'>
									<option value='1'>1</option>
									<option value='2'>2</option>
									<option value='3'>3</option>
									<option value='4'>4</option>
									<option value='5'>5</option>
								</select>
							</div>
							<div class="form-group">
								<input type="submit" value="Rate Meal" class='btn btn-danger'>
							</div>
						</form>
					{% endif %}
					{% if request.session.id != recipe.creator.id %}
						{% if user in recipe.user.all %}
							<p><a href="{% url 'main:save_recipe' recipe_id=recipe.id %}">Unsave This Recipe</a></p>
						{% else %}
							<p><a href="{% url 'main:save_recipe' recipe_id=recipe.id %}">Save This Recipe</a></p>
						{% endif %}
					{% endif %}
					<p><b>Prep Time:</b> {{recipe.prep_time_hour}} hour(s), {{recipe.prep_time_minute}} minutes.</p>
					<p><b>Cook Time:</b> {{recipe.cook_time_hour}}  hour(s), {{recipe.cook_time_minute}} minutes.</p>
					<p><b>Total Time:</b> {{total_time_hour}} hour(s), {{total_time_minute}} minutes.</p>
					<p><b>Description: </b>{{recipe.description}}</p>
					<p><b>Categories:</b>
						{% for category in recipe.categories.all %}
							{% if recipe.categories.all|length > 1 and forloop.counter < recipe.categories.all|length %}
								{{category.category}},
							{% else %}
								{{category.category}}
							{% endif %}
						{% endfor %}
					</p>
					{% if request.session.id == recipe.creator.id %}
					<a href="{% url 'main:edit_recipe' recipe_id=recipe.id %}"><button class='btn btn-danger'>Edit this Recipe</button></a>
					{% endif %}
				</div>
			</div>
			<hr>
			<div class="steps">
				<p><b>Steps:</b></p>
				<ol>
					{% for step in recipe.steps.all %}
					<li>{{step.measurement.measurement}} of {{step.ingredient.ingredient}} <br>{{step.description}}</li>
					{% endfor %}
				</ol>
				<hr>
			</div>
			<h3> Comments </h3>
			<div id="comments">
				{% for comment in recipe.comments.all %}
					<p>{{comment.created_at}} <b>{{ comment.user.first_name }}</b> commented: </p>
					<p class='comment'>{{ comment.comment }}</p>
				{% endfor %}
			</div>
			<h4>Add a comment:</h4>
			<form action="{% url 'main:show_recipe' recipe_id=recipe.id %}" method="post" class='form-horizontal'>
				{% csrf_token %}
				<div class="form-group">
					<textarea class='from-control' name='comment' rows="5" cols="25" placeholder="Write a comment..."></textarea>
				</div>
				<div class="form-group">
					<input type="submit" value="Post" class='btn btn-danger'>
				</div>
			</form>
		</div>
	</div>
</div>

</body>
</html>